# Generated by Django 2.2 on 2019-07-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20190701_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='periodend',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='periodstart',
            new_name='startdate',
        ),
    ]
